# Generated by Django 2.2 on 2020-05-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
