# Generated by Django 3.1 on 2020-09-03 18:24

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='body',
            field=django_cryptography.fields.encrypt(models.TextField()),
        ),
    ]
