# Generated by Django 2.2 on 2020-05-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Note', '0002_auto_20200523_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date_added',
            field=models.DateTimeField(),
        ),
    ]
