# Generated by Django 3.1 on 2020-09-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Note', '0003_note_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
